{{-- 
    required variables:
    
    $form_open = form open HTML generated by laravel collective
    $submit_button_text 
--}}


{{ $form_open }}
<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            {!! Form::label('actor_fullname', null, ['class' => 'form-label']) !!}
            {!! Form::text('actor_fullname', null, ['class'=>'form-control', 'required']) !!}
            @error('actor_fullname')
                <p class="alert alert-danger">{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('actor_notes', null, ['class' => 'form-label']) !!}
            {!! Form::text('actor_notes', null, ['class'=>'form-control']) !!}
            @error('actor_notes')
                <p class="alert alert-danger">{{ $message }}</p>
            @enderror
        </div>
        {!! Form::submit($submit_button, ['class'=>"btn btn-primary"]) !!}

    </div>
    <div class="col-lg-6">
        {{-- to house the image upload form input later --}}
    </div>
</div>


{!! Form::close() !!}