{{--
    $form_open = form HTML generated by laravelcollective
--}}

{{$form_open}}
<div class="form-group">
    {!! Form::label("role", "Role", ['class' => 'form-label']) !!}
    {!! Form::text("role", null, ['class' => 'form-control', 'required']) !!}
</div>
    {!! Form::submit($form_submit, ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}